assign/assign/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import assistant.views as views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('assistant.urls',namespace='assistant')),
]

assign/assistant/urls.py
from django.conf.urls import url
from assistant import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required, permission_required
app_name = 'assistant'

urlpatterns = [
    
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^home',views.HomeView.as_view(),name='home'),
    url(r'^post/new/$',views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.Post_publish, name='post_publish'),
    url(r"^login/$", auth_views.LoginView.as_view(template_name="assistant/login.html"),name='login'),
    url(r"^logout/$", login_required(auth_views.LogoutView.as_view()), name="logout"),
    url(r"^signup/$", views.SignUp.as_view(), name="signup"),
    url(r"^contact/$", permission_required('assistant.view_contact',raise_exception=True)(views.ContactListView.as_view()), name="contact"),
    url(r"^description/$", login_required(views.DescriptionListView.as_view()), name="description"),
    url(r'^healthstatus/(?P<pk>\d+)$',login_required(views.HealthDetailView.as_view()),name='healthstatus'),
    url(r'^healthlist/$',permission_required('assistant.create_review')(views.HealthListView.as_view()),name="health_list"),
    url(r'^healthstatus/(?P<pk>\d+)/comment/$', permission_required('assistant.create_review')(views.add_comment_to_post), name='add_comment_to_post'),
    url(r'^healthstatus/(?P<pk>\d+)/approve/$', permission_required('assistant.create_review')(views.comment_approve), name='comment_approve'),
    url(r'^healthstatus/(?P<pk>\d+)/remove/$', permission_required('assistant.create_review')(views.comment_remove), name='comment_remove'),
]

assign/assistant/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
# Create your models here.
class Post(models.Model):
    #author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('assistant:post_detail',kwargs={'pk':self.pk})

class Task(models.Model):
    
    class Meta:
        permissions = (
            ("create_post", "Can create announcement"),
            ("view_contact","Can view emergency contact"),
            ("create_review","Doctor create review"),
        )

class Contact(models.Model):
    title = models.CharField(max_length=200)
    number = models.CharField(max_length=200)
    published_date = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.title

class Description(models.Model):
    functionality = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    published_date = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.functionality

class HealthStatus(models.Model):
    patientid = models.OneToOneField(User,primary_key=True)
    status = models.TextField()
    def __str__(self):
        return str(self.patientid)

class Comment(models.Model):
    post = models.ForeignKey('assistant.HealthStatus', related_name='recommendation')
    doctor = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self):
        return self.text

assign/assistant/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post,Comment
from django.contrib.auth import get_user_model

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','text','created_date','published_date')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('doctor', 'text',)

        widgets = {
            'doctor': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

assign/assistant/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin as LoginRequiredMixin1
from django.contrib.auth.decorators import login_required,permission_required
from .forms import UserCreateForm,PostForm,CommentForm
from django.contrib.auth.models import Group,User
from .models import Post,Contact,Description,HealthStatus,Comment
from django.contrib.auth import authenticate,login,logout
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied
# def group_required(*group_names):
#     """Requires user membership in at least one of the groups passed in."""
#     def in_groups(u):
#         if u.is_authenticated():
#             if bool(u.groups.filter(name__in=group_names)) | u.is_superuser:
#                 return True
#         #return False
#         raise PermissionDenied
#         #redirect('assistant:home')
#     return user_passes_test(in_groups)
# Create your views here.
class SignUp(CreateView):
    form_class = UserCreateForm

    def get_success_url(self):
        g = Group.objects.get(name='user')
        g.user_set.add(self.object)
        uid = User.objects.latest('id')
        h ,created = HealthStatus.objects.get_or_create(
            patientid = uid,
            defaults = {'status':'new user!'}
        )
        return reverse_lazy("assistant:login")
    #success_url = reverse_lazy("assistant:login")
    template_name = "assistant/signup.html"

class HomeView(TemplateView):
    template_name = 'home.html'



# def class_view_decorator(function_decorator):
#     """Convert a function based decorator into a class based decorator usable
#     on class based Views.

#     Can't subclass the `View` as it breaks inheritance (super in particular),
#     so we monkey-patch instead.
#     """
#     def simple_decorator(View):
#         View.dispatch = method_decorator(function_decorator)(View.dispatch)
#         return View

#     return simple_decorator

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post

#@class_view_decorator(permission_required('create_post'))
#@method_decorator(group_required('doctor'),name='dispatch')
class LoginRequiredMixin(object):
    @method_decorator(permission_required('assistant.create_post',raise_exception=True))
    #@method_decorator(group_required('doctor'))
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)

class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'assistant/post_detail.html'

    form_class = PostForm

    model = Post

@login_required
def Post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('assistant:post_detail', pk=pk)

class ContactListView(ListView):
    model = Contact

    def get_queryset(self):
        return Contact.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class DescriptionListView(ListView):
    model = Description

    def get_queryset(self):
        return Description.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class HealthDetailView(DetailView):
    model = HealthStatus

#@permission_required('assistant.create_review')
def add_comment_to_post(request, pk):
    post = get_object_or_404(HealthStatus, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('assistant:healthstatus', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'assistant/progress_form.html', {'form': form})    

class HealthListView(ListView):
    model = HealthStatus

    def get_queryset(self):
        return HealthStatus.objects.order_by('-patientid')


def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('assistant:healthstatus', pk=comment.post.pk)



def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('assistant:healthstatus', pk=post_pk)

assign/templates/assistant/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Health assistant</title>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'acss/master.css'%}">
    </head>
    <body>
        <nav class='navbar mynav' role='navigation' id='navbar'>
            <div class="container">
                <a class='navbar-brand mynav' href="{% url 'assistant:home' %}">Health Assistant</a>
                <ul class='nav navbar-nav navbar-right'>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'assistant:description' %}">Functionality</a></li>
                        <li><a href="{% url 'assistant:post_list' %}">Announcement</a></li>
                        {% if perms.assistant.view_contact %}
                        <li><a href="{% url 'assistant:contact' %}" >Emergency</a></li>
                        {% endif %}
                        {% if perms.assistant.create_review %}
                            <li><a href="{% url 'assistant:health_list' %}">Patient list</a></li>
                        {% endif %}
                        {% if perms.assistant.view_contact %}
                            <li><a href="{% url 'assistant:healthstatus' pk=user.pk %}">Personal Health</a></li>
                        {% endif %}
                        {% comment %} <li><a href="{% url 'assistant:healthstatus' pk=user.pk %}">Health Status</a></li> {% endcomment %}
                        {% if perms.assistant.create_review %}
                            <li><a href="{% url 'assistant:post_new' %}" >Post Announcement</a></li>
                        {% endif %}
                        <li><a href="#">{{  user.username }}</a></li>
                        <li><a href="{% url 'assistant:logout' %}">Log out</a></li>
                        
                    {% else %}
                        <li><a href="#">Announcement</a></li>
                        <li><a href="{% url 'assistant:login' %}">Log in</a></li>
                        <li><a href="{% url 'assistant:signup' %}">Sign up</a></li>
                    {% endif %}
                </ul>
                

            </div>
        </nav>
        <div class="container mycontent">
            
            {% block content %}
        
            {% endblock content %}
            
        </div>
    </body>
</html>

assign/templates/assistant/contact_list.html
{% extends "assistant/base.html" %}
{% block content %}
<div class="centerstage">
        {% for post in contact_list %}
            <div class="post">
    
                <h1>Emergency Title: {{ post.title }}</h1>
                <h3>Contact: {{ post.number}}</h3>
                <div class="date">
                    <p>Published on: {{ post.published_date|date:"D M Y"}}</p>
                </div>
                
            </div>
        {% endfor %}
    </div>
{% endblock content %}

assign/templates/assistant/description_list.html
{% extends "assistant/base.html" %}
{% block content %}
<div class="centerstage">
        {% for post in description_list %}
            <div class="post">
    
                <h3>Functionality: {{ post.functionality }}</h3>
                <p>Description: {{ post.description }}</p>
                <!-- <div class="date">
                    <p>Published on: {{ post.published_date|date:"D M Y"}}</p>
                </div>                -->
            </div>
        {% endfor %}
    </div>
{% endblock content %}

assign/templates/assistant/healthstatus_detail.html
{% extends "assistant/base.html" %} 
{% block content %}
<div class="centerstage">
    <p>Welcome to {{ healthstatus.patientid }} health page. Thanks for logging in.</p>
    <p>{{ healthstatus.patientid }} health status is:{{ healthstatus.status }}</p>

</div>
<hr>
{% if perms.assistant.create_review %}
<a class="btn btn-primary btn-comment" href="{% url 'assistant:add_comment_to_post' pk=healthstatus.pk %}">Add Recommendation</a>
{% endif %}
<div class="container">
    {% for comment in healthstatus.recommendation.all %}
    <br> 
        {% if user.is_authenticated %} 
            {{ comment.created_date }} 
            {% if not comment.approved_comment %}
            <a class="btn btn-default" href="{% url 'assistant:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
            <a class="btn btn-default" href="{% url 'assistant:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
            {% endif %}

        <p>{{ comment.text|safe|linebreaks }}</p>
        <p>Posted by:
            <strong>{{ comment.doctor }}</strong>
        </p>
        
        {% endif %} 
    {% empty %}
    <p>No Recommendation</p>
    {% endfor %}
</div>
{% endblock content %}

assign/templates/assistant/healthstatus_list.html
{% extends "assistant/base.html" %}
{% block content %}
<div class="centerstage">
    
    
        {% for post in healthstatus_list %}
            <div class="healthstatus">
    
                <h1><a href="{% url 'assistant:healthstatus' pk=post.pk %}">{{ post.patientid }}</a></h1>
                
                <a href="{% url 'assistant:healthstatus' pk=post.pk %}">detail</a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

assign/templates/assistant/home.html
{% extends "assistant/base.html" %}
{% block content %}
    <h1>Welcome to assistant</h1>
{% endblock content %}

assign/templates/assistant/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

assign/templates/assistant/post_detail.html
{% extends 'assistant/base.html' %}

{% block content %}


        <h1 class='posttitle loader'>{{ post.title }}</h1>

        {% if post.published_date %}
            <div class="date postdate">
                {{ post.published_date }}
            </div>

        {% else %}
            <a class="btn btn-default" href="{% url 'assistant:post_publish' pk=post.pk %}">Publish</a>
        {% endif %}

      <p class='postcontent' >{{ post.text|safe|linebreaksbr }}</p>
  <hr>
  <div class="container">
</div>

{% endblock %}

assign/templates/assistant/post_draft_list.html
{% extends 'assistant/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

assign/templates/assistant/post_form.html
{% extends 'assistant/base.html' %}

{% block content %}
    <h1>New post</h1>

    <form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

assign/templates/assistant/post_list.html
{% extends "assistant/base.html" %}
{% block content %}
<div class="centerstage">
    
    <h1>Announcement</h1>
        {% for post in post_list %}
            <div class="post">
    
                <h1><a href="{% url 'assistant:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                <div class="date">
                    <p>Published on: {{ post.published_date|date:"D M Y"}}</p>
                </div>
                <a href="{% url 'assistant:post_detail' pk=post.pk %}">detail</a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

assign/templates/assistant/progress_form.html
{% extends 'assistant/base.html' %}

{% block content %}
    <h1>New Progress</h1>
    <form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Add Progress</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

assign/templates/assistant/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}