assign/assign/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import assistant.views as views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('assistant.urls',namespace='assistant')),
]

assign/assistant/urls.py
from django.conf.urls import url
from assistant import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required, permission_required
app_name = 'assistant'

urlpatterns = [
    
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^home',views.HomeView.as_view(),name='home'),
    url(r'^post/new/$',views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.Post_publish, name='post_publish'),
    url(r"^login/$", auth_views.LoginView.as_view(template_name="assistant/login.html"),name='login'),
    url(r"^logout/$", login_required(auth_views.LogoutView.as_view()), name="logout"),
    url(r"^signup/$", views.SignUp.as_view(), name="signup"),
    url(r"^contact/$", permission_required('assistant.view_contact',raise_exception=True)(views.ContactListView.as_view()), name="contact"),
    url(r"^description/$", login_required(views.DescriptionListView.as_view()), name="description"),
    url(r'^healthstatus/(?P<pk>\d+)$',login_required(views.HealthDetailView.as_view()),name='healthstatus'),
    url(r'^healthlist/$',permission_required('assistant.create_review')(views.HealthListView.as_view()),name="health_list"),
    url(r'^healthstatus/(?P<pk>\d+)/comment/$', permission_required('assistant.create_review')(views.add_comment_to_post), name='add_comment_to_post'),
    url(r'^healthstatus/(?P<pk>\d+)/approve/$', permission_required('assistant.create_review')(views.comment_approve), name='comment_approve'),
    url(r'^healthstatus/(?P<pk>\d+)/remove/$', permission_required('assistant.create_review')(views.comment_remove), name='comment_remove'),
]

assign/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Health assistant</title>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'as/css/master.css'%}">
    </head>
    <body>
        <nav class='navbar mynav' role='navigation' id='navbar'>
            <div class="container">
                <a class='navbar-brand mynav' href="{% url 'assistant:home' %}">Health Assistant</a>
                <ul class='nav navbar-nav navbar-right'>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'assistant:post_list' %}">Main page</a></li>
                        <li><a href="#">{{  user.username }}</a></li>
                        <li><a href="{% url 'assistant:logout' %}">Log out</a></li>
                    {% else %}
                        <li><a href="#">Announcement</a></li>
                        <li><a href="{% url 'assistant:login' %}">Log in</a></li>
                        <li><a href="{% url 'assistant:signup' %}">Sign up</a></li>
                    {% endif %}
                </ul>
                

            </div>
        </nav>
        <div class="container mycontent">
        {% block content %}
        
        {% endblock content %}
        </div>
    </body>
</html>

assign/templates/home.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome to assistant</h1>
{% endblock content %}